### ISSUE TITLE
Error al iniciar un nodo validador de 0

### ISSUE THREAD

**Issue by marcossanlab** [alastria/alastria-node#71]
Según se arranca la primera vez e intenta sincronizar con el resto de nodos validadores, genera este error:
NFO [01-03|10:31:26] Block synchronisation started
INFO [01-03|10:31:26] Mining aborted due to sync
INFO [01-03|10:31:26] Imported new chain segment               blocks=192 txs=0 mgas=0.000 elapsed=167.428ms mgasps=0.000 number=192 hash=ec983b…d15db0
panic: runtime error: index out of range

goroutine 45 [running]:
panic(0xef9460, 0xc4200120e0)
       /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/core/types.NewTransactionsByPriceAndNonce(0x192e620, 0xc4223f1450, 0xc4224a3d10, 0x0)
       /root/alastria-node/scripts/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/transaction.go:399 +0x475
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc42000e280)
       /root/alastria-node/scripts/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:463 +0x97b
github.com/ethereum/go-ethereum/miner.(*worker).update(0xc42000e280)
       /root/alastria-node/scripts/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:259 +0x232
created by github.com/ethereum/go-ethereum/miner.newWorker
       /root/alastria-node/scripts/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:158 +0x5ea

Se arranca de nuevo el nodo y sincroniza correctamente.

**Comment by marcossanlab** [comment]
Resuelto al actualizar la versión de Quorum.
